/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jvananagramas;

import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author efras
 */
public class jfrmAnanagrama extends javax.swing.JFrame {
    // Modelo de los datos de la lista
    URL urlImagen;
    clsAnanagrama objAnanagrama;
    DefaultListModel valoresLsIngresar;
    DefaultListModel ananagramasLsEncontrados;
    String valorLst1 = "";
    String valorLst2 = "";
    /**
     * Creates new form jfrmAnanagrama
     */
    public jfrmAnanagrama() {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        mostrarImagen(jlblLogo, "/images/logo.jpg");
        valoresLsIngresar = new DefaultListModel();
        jlstPalabrasIngresadas.setModel(valoresLsIngresar);
        ananagramasLsEncontrados = new DefaultListModel();
        jlstAnanagramas.setModel(ananagramasLsEncontrados);
        this.jtxtNumAnanagramas.setEditable(false);
        objAnanagrama = new clsAnanagrama();
    }
    public void mostrarImagen(JLabel imagenLogo, String urlImg){
        //Se esta asignando la url donde se encuentra la imagen
        //a la variable que se declaro como URL
        urlImagen = this.getClass().getResource(urlImg);
        //se genera un icono
        ImageIcon imgL = new ImageIcon(urlImagen);
        //Se configura la imagen al tamaño del control donde se va a mostrar
        Icon imagen = new ImageIcon(imgL.getImage().getScaledInstance(imagenLogo.getWidth(), imagenLogo.getHeight(), Image.SCALE_DEFAULT));
        //Se asigna a la etiqueta
        imagenLogo.setIcon(imagen);
        //Hace que se vea la imagen en la etiqueta, sino se coloca
        //no se ve
        this.repaint();
    } 
    public void limpiarControles(){
        valoresLsIngresar.clear();
        ananagramasLsEncontrados.clear();
        jtxtNumAnanagramas.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlblNumAnanagramas = new javax.swing.JLabel();
        jtxtNumAnanagramas = new javax.swing.JTextField();
        jlblPalabrasIng = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlstPalabrasIngresadas = new javax.swing.JList<>();
        jlblAnanagramaEncont = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlstAnanagramas = new javax.swing.JList<>();
        jbtnIngresar = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ananagramas");

        jlblNumAnanagramas.setForeground(new java.awt.Color(255, 255, 255));
        jlblNumAnanagramas.setText("Número de palabras a ingresar:");

        jlblPalabrasIng.setForeground(new java.awt.Color(255, 255, 255));
        jlblPalabrasIng.setText("Palabras ingresadas:");

        jlstPalabrasIngresadas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlstPalabrasIngresadas);

        jlblAnanagramaEncont.setForeground(new java.awt.Color(255, 255, 255));
        jlblAnanagramaEncont.setText("Ananagramas encontrados:");

        jlstAnanagramas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jlstAnanagramas);

        jbtnIngresar.setBackground(new java.awt.Color(0, 0, 0));
        jbtnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnIngresar.setText("Generar Palabras");
        jbtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresarActionPerformed(evt);
            }
        });

        jbtnLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        jbtnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpiarActionPerformed(evt);
            }
        });

        jbtnSalir.setBackground(new java.awt.Color(0, 0, 0));
        jbtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSalir.setText("Cerrar");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnIngresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnSalir)
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblNumAnanagramas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtNumAnanagramas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblPalabrasIng)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblAnanagramaEncont))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jbtnLimpiar))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNumAnanagramas)
                    .addComponent(jtxtNumAnanagramas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPalabrasIng)
                    .addComponent(jlblAnanagramaEncont))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnIngresar)
                    .addComponent(jbtnLimpiar)
                    .addComponent(jbtnSalir))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresarActionPerformed
        // TODO add your handling code here:
        boolean repetirPalabra = true;
        objAnanagrama.generarPalabras();
        String[]arrPalabras = new String[objAnanagrama.getNumPalabras()];
        // Quitar valores null
        for (int i = 0; i < objAnanagrama.getNumPalabras(); i++) {
            arrPalabras[i] = "";
        }
        jtxtNumAnanagramas.setText(String.valueOf(objAnanagrama.getNumPalabras()));
        JOptionPane.showMessageDialog(null, "Ingresa " + objAnanagrama.getNumPalabras() + " palabras:");
        for (int i = 0; i < objAnanagrama.getNumPalabras(); i++) {
            while (repetirPalabra) {                
                valorLst1 = JOptionPane.showInputDialog(null, "Ingresa la palabra " + (i+1) + ":");
                if (objAnanagrama.validadPalabra(valorLst1, arrPalabras) == 0) {
                    arrPalabras[i] = objAnanagrama.normalizarPalabra(valorLst1);
                    repetirPalabra = false;
                } else if (objAnanagrama.validadPalabra(valorLst1, arrPalabras) == 1){
                    JOptionPane.showMessageDialog(null, "Ingresa una palabra de mímino 3 letras y máximo 20");
                } else if (objAnanagrama.validadPalabra(valorLst1, arrPalabras) == 2){
                    JOptionPane.showMessageDialog(null, "Ingresa una palabra sin espacios");
                } else if (objAnanagrama.validadPalabra(valorLst1, arrPalabras) == 3){
                    JOptionPane.showMessageDialog(null, "Ingresa una palabra que no hayas ingresado antes");
                } else if (objAnanagrama.validadPalabra(valorLst1, arrPalabras) == 4){
                    JOptionPane.showMessageDialog(null, "Ingresa solo letras, no números");
                } 
            }
            repetirPalabra = true;
        }
        valoresLsIngresar.clear();
        for (int i = 0; i < arrPalabras.length; i++) {
            valoresLsIngresar.addElement(arrPalabras[i]);
        }
        ananagramasLsEncontrados.clear();
        objAnanagrama.setArrPalabras(objAnanagrama.ordenarPalabras(arrPalabras));
        objAnanagrama.validarAnagrama();
        if (objAnanagrama.getArrAnanagrama().length<1) {
            ananagramasLsEncontrados.addElement("No hay ananagramas");
        }else{
            for (int i = 0; i < objAnanagrama.getArrAnanagrama().length; i++) {
                ananagramasLsEncontrados.addElement(objAnanagrama.getArrAnanagrama()[i]);
            }
        }
        
        
        
    }//GEN-LAST:event_jbtnIngresarActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarControles();
        objAnanagrama.limpiarObjetos();
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmAnanagrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmAnanagrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmAnanagrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmAnanagrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmAnanagrama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnIngresar;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JLabel jlblAnanagramaEncont;
    private javax.swing.JLabel jlblLogo;
    private javax.swing.JLabel jlblNumAnanagramas;
    private javax.swing.JLabel jlblPalabrasIng;
    private javax.swing.JList<String> jlstAnanagramas;
    private javax.swing.JList<String> jlstPalabrasIngresadas;
    private javax.swing.JTextField jtxtNumAnanagramas;
    // End of variables declaration//GEN-END:variables
}
